grafana:
  adminPassword: polycode-grafana
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-issuer
    hosts:
      - grafana.staging.polycode.do-2021.fr
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.staging.polycode.do-2021.fr

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    probeSelectorNilUsesHelmValues: false
