FROM node:16-alpine

LABEL MAINTAINER="iverly <contact@polycode.dopolytech.fr>"
LABEL APP="polycode-api"

WORKDIR /usr/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy files and build the application
COPY . .
RUN npm run build runner

# Run the linter & tests
RUN npm run lint
RUN npm run test

# Cleanup
RUN rm -rf libs/

EXPOSE 3001
CMD ["node", "dist/apps/runner/main.js"]
