FROM node:16-alpine

LABEL MAINTAINER="iverly <contact@polycode.dopolytech.fr>"
LABEL APP="polycode-api"

WORKDIR /usr/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy files and build the application
COPY . .
RUN npm run build api

# Cleanup
RUN rm -rf libs/

EXPOSE 3000
CMD ["node", "dist/apps/api/main.js"]
