FROM node:16-alpine

LABEL MAINTAINER="Simon LUCIDO <simon.lucido@etu.umontpellier.fr>"
LABEL APP="polycode-runner"

WORKDIR /usr/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy files and build the application
COPY . .
RUN npm run build runner

# Cleanup
RUN rm -rf libs/

EXPOSE 3001
CMD ["node", "dist/apps/runner/main.js"]
