{{- if .Values.sealedSecrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secrets
spec:
  encryptedData:
    {{- if .Values.sealedSecrets.keycloak }}
    keycloak-secret: {{ .Values.sealedSecrets.keycloak.secret | quote }}
    keycloak-public-key: {{ .Values.sealedSecrets.keycloak.publickey | quote }}
    {{- end }}

    {{- if .Values.sealedSecrets.postgres }}
    postgres-host: {{ .Values.sealedSecrets.postgres.host | quote }}
    postgres-port: {{ .Values.sealedSecrets.postgres.port | quote }}
    postgres-user: {{ .Values.sealedSecrets.postgres.user | quote }}
    postgres-password: {{ .Values.sealedSecrets.postgres.password | quote }}
    postgres-database: {{ .Values.sealedSecrets.postgres.database | quote }}
    {{- end }}

    {{- if .Values.sealedSecrets.mongodb }}
    mongodb-url: {{ .Values.sealedSecrets.mongodb.url | quote }}
    mongodb-user: {{ .Values.sealedSecrets.mongodb.user | quote }}
    mongodb-password: {{ .Values.sealedSecrets.mongodb.password | quote }}
    {{- end }}

    {{- if .Values.sealedSecrets.email }}
    email-provider: {{ .Values.sealedSecrets.email.provider | quote }}
    
    {{- if .Values.sealedSecrets.email.ses }}
    email-ses-access-key: {{ .Values.sealedSecrets.email.ses.access.key | quote }}
    email-ses-secret-key: {{ .Values.sealedSecrets.email.ses.secret.key | quote }}
    email-ses-region: {{ .Values.sealedSecrets.email.ses.region | quote }}
    {{- end }}

    {{- if .Values.sealedSecrets.email.smtp }}
    email-smtp-host: {{ .Values.sealedSecrets.email.smtp.host | quote }}
    email-smtp-port: {{ .Values.sealedSecrets.email.smtp.port | quote }}
    email-smtp-user: {{ .Values.sealedSecrets.email.smtp.user | quote }}
    email-smtp-password: {{ .Values.sealedSecrets.email.smtp.password | quote }}
    {{- end }}
    {{- end }}
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: api-secrets
{{- end }}
