server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - argo.polycode.127.0.0.1.sslip.io
  insecure: true # disable force tls from argo
  additionalApplications:
    - name: local-frontend
      namespace: argo-cd
      project: local
      source:
        repoURL: https://github.com/polycode-lucido/oidc-poc.git
        targetRevision: HEAD
        path: frontend/helm/chart
        helm:
          releaseName: frontend
          valueFiles:
            - ../local.values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: polycode
    - name: local-api
      namespace: argo-cd
      project: local
      source:
        repoURL: https://github.com/polycode-lucido/oidc-poc.git
        targetRevision: HEAD
        path: backend/helm/api/chart
        helm:
          releaseName: backend
          valueFiles:
            - ../local.values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: polycode 
    - name: local-runner
      namespace: argo-cd
      project: local
      source:
        repoURL: https://github.com/polycode-lucido/oidc-poc.git
        targetRevision: HEAD
        path: backend/helm/runner/chart
        helm:
          releaseName: runner
          valueFiles:
            - ../local.values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: polycode 
    - name: postgresql
      namespace: argo-cd
      project: default
      source:
        repoURL: 'https://github.com/bitnami/charts.git'
        path: bitnami/postgresql-ha
        targetRevision: HEAD
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: polycode
      helm:
        releaseName: postgresql
    - name: mongodb
      namespace: argo-cd
      project: default
      source:
        repoURL: 'https://github.com/bitnami/charts.git'
        path: bitnami/mongodb
        targetRevision: HEAD
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: polycode
      helm:
        releaseName: mongodb

  additionalProjects:
    - name: local
      namespace: argo-cd
      description: Polycode Local Project
      sourceRepos:
        - https://github.com/polycode-lucido/oidc-poc.git
      destinations:
        - namespace: polycode
          server: https://kubernetes.default.svc
configs:
  repositories:
    frontend:
      url: https://github.com/polycode-lucido/oidc-poc.git
      name: frontend
    backend:
      url: https://github.com/polycode-lucido/oidc-poc.git
      name: backend
