server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-issuer
      # For 307 errors force https
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    hosts:
      - argo.polycode.do-2021.fr
    tls:
      - secretName: argo-tls
        hosts:
          - argo.polycode.do-2021.fr
  additionalApplications:
    - name: prod-frontend
      namespace: argo-cd
      project: prod
      source:
        repoURL: git@gitlab.polytech.umontpellier.fr:do-polycode/frontend.git
        targetRevision: HEAD
        path: helm/chart
        helm:
          releaseName: frontend
          valueFiles:
            - ../prod.values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: polycode
    - name: prod-api
      namespace: argo-cd
      project: prod
      source:
        repoURL: git@gitlab.polytech.umontpellier.fr:do-polycode/backend.git
        targetRevision: HEAD
        path: helm/api/chart
        helm:
          releaseName: backend
          valueFiles:
            - ../prod.values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: polycode
    - name: prod-runner
      namespace: argo-cd
      project: prod
      source:
        repoURL: git@gitlab.polytech.umontpellier.fr:do-polycode/backend.git
        targetRevision: HEAD
        path: helm/runner/chart
        helm:
          releaseName: runner
          valueFiles:
            - ../prod.values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: polycode
    - name: staging-frontend
      namespace: argo-cd
      project: staging
      source:
        repoURL: git@gitlab.polytech.umontpellier.fr:do-polycode/frontend.git
        targetRevision: HEAD
        path: helm/chart
        helm:
          releaseName: frontend
          valueFiles:
            - ../staging.values.yaml
      destination:
        server: https://staging.polycode.do-2021.fr
        namespace: polycode
      syncPolicy:
        automated: {}
    - name: staging-api
      namespace: argo-cd
      project: staging
      source:
        repoURL: git@gitlab.polytech.umontpellier.fr:do-polycode/backend.git
        targetRevision: HEAD
        path: helm/api/chart
        helm:
          releaseName: backend
          valueFiles:
            - ../staging.values.yaml
      destination:
        server: https://staging.polycode.do-2021.fr
        namespace: polycode
      syncPolicy:
        automated: {}
    - name: staging-runner
      namespace: argo-cd
      project: staging
      source:
        repoURL: git@gitlab.polytech.umontpellier.fr:do-polycode/backend.git
        targetRevision: HEAD
        path: helm/runner/chart
        helm:
          releaseName: runner
          valueFiles:
            - ../staging.values.yaml
      destination:
        server: https://staging.polycode.do-2021.fr
        namespace: polycode
      syncPolicy:
        automated: {}
  additionalProjects:
    - name: prod
      namespace: argo-cd
      description: Polycode Prod Project
      sourceRepos:
        - git@gitlab.polytech.umontpellier.fr:do-polycode/frontend.git
        - git@gitlab.polytech.umontpellier.fr:do-polycode/backend.git
      destinations:
        - namespace: polycode
          server: https://kubernetes.default.svc
    - name: staging
      namespace: argo-cd
      description: Polycode Staging Project
      sourceRepos:
        - git@gitlab.polytech.umontpellier.fr:do-polycode/frontend.git
        - git@gitlab.polytech.umontpellier.fr:do-polycode/backend.git
      destinations:
        - namespace: polycode
          server: https://staging.polycode.do-2021.fr
configs:
  repositories:
    frontend:
      url: git@gitlab.polytech.umontpellier.fr:do-polycode/frontend.git
      name: frontend
    backend:
      url: git@gitlab.polytech.umontpellier.fr:do-polycode/backend.git
      name: backend
  knownHosts:
    data:
      ssh_known_hosts: |
        gitlab.polytech.umontpellier.fr ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBwrfX+ORYpnJXbL147VngSjRh581nL2pC5acEC9p9Zz
        gitlab.polytech.umontpellier.fr ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLdTyDhj8idM5LvRVraa3Hcy877xd8T8q0xDzIYI+GdEbKOc+eN4Gqf9QlrKqfSHNo4ydzM8Wwoah+xehGUrYrM=
