server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-issuer
      # For 307 errors force https
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    hosts:
      - argo.poly-code.com
    # tls:
      # - secretName: argo-tls
        # hosts:
          # - argo.poly-code.com
  additionalApplications:
    - name: prod-frontend
      namespace: argo-cd
      project: prod
      source:
        repoURL: https://github.com/polycode-lucido/oidc-poc.git
        targetRevision: HEAD
        path: frontend/helm/chart
        helm:
          releaseName: frontend
          valueFiles:
            - ../prod.values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: polycode
    - name: prod-api
      namespace: argo-cd
      project: prod
      source:
        repoURL: https://github.com/polycode-lucido/oidc-poc.git
        targetRevision: HEAD
        path: backend/helm/api/chart
        helm:
          releaseName: backend
          valueFiles:
            - ../prod.values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: polycode
    - name: prod-runner
      namespace: argo-cd
      project: prod
      source:
        repoURL: https://github.com/polycode-lucido/oidc-poc.git
        targetRevision: HEAD
        path: backend/helm/runner/chart
        helm:
          releaseName: runner
          valueFiles:
            - ../prod.values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: polycode
  additionalProjects:
    - name: prod
      namespace: argo-cd
      description: Polycode Prod Project
      sourceRepos:
        - https://github.com/polycode-lucido/oidc-poc.git
      destinations:
        - namespace: polycode
          server: https://kubernetes.default.svc
configs:
  repositories:
    frontend:
      url: https://github.com/polycode-lucido/oidc-poc.git
      name: frontend
    backend:
      url: https://github.com/polycode-lucido/oidc-poc.git
      name: backend
