variable "kubeconfig_context_name" {
  type    = string
  default = "k3d-kube-polycode-local"
}

variable "kubeconfig_path" {
  type    = string
  default = "~/.kube/config"
}

variable "grafana_admin_password" {
  type        = string
  description = "Grafana admin password"
  default     = "admin"
  sensitive   = true
}

variable "argo_cd_admin_password" {
  type        = string
  description = "Argo CD bcrypt hashed admin password"
  default     = "$2y$10$adCiprUiugTubOEkA49aierhMbxym5Q3T5M3FAXLZ3qKpq3q1gWyS"
  sensitive   = true
}

variable "gitlab_deploy_key" {
  type        = string
  description = "The path to the private key used to connect to the Gitlab repositories"
  sensitive   = true
}

variable "container_registry_password" {
  type        = string
  description = "The password generated by the deploy token used to access the container registry"
  sensitive   = true
}
