{{- if .Values.role.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.role.name }}
{{- with .Values.role.rules }}
rules:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
