{{- if .Values.roleBinding.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.roleBinding.name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "backend.serviceAccountName" . }}
    apiGroup: ""
roleRef:
  kind: Role
  name: {{ .Values.role.name }}
  apiGroup: ""
{{- end }}
