# Local values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

env:
  - name: PUBLIC_API_URL
    value: http://api.polycode.127.0.0.1.sslip.io

ingress:
  hosts:
    - host: www.polycode.127.0.0.1.sslip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: polycode.127.0.0.1.sslip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
