# Prod values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

env:
  - name: NEXT_PUBLIC_API_URL
    value: https://api.poly-code.com

ingress:
  hosts:
    - host: www.poly-code.com
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: poly-code.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  # tls:
  #   - secretName: frontend-www-tls
  #     hosts:
  #       - www.poly-code.com
  #   - secretName: frontend-tls
  #     hosts:
  #       - poly-code.com
