# Prod values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

env:
  - name: PUBLIC_API_URL
    value: https://api.polycode.simonlucido.com

ingress:
  hosts:
    - host: www.polycode.simonlucido.com
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: polycode.simonlucido.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: frontend-www-tls
      hosts:
        - www.polycode.simonlucido.com
    - secretName: frontend-tls
      hosts:
        - polycode.simonlucido.com
