# Staging values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

env:
  - name: PUBLIC_API_URL
    value: https://api.staging.polycode.do-2021.fr

ingress:
  hosts:
    - host: www.staging.polycode.do-2021.fr
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: staging.polycode.do-2021.fr
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: frontend-www-tls
      hosts:
        - www.staging.polycode.do-2021.fr
    - secretName: frontend-tls
      hosts:
        - staging.polycode.do-2021.fr
