stages:
  - provision
  - deploy

include:
  - remote: https://api.r2devops.io/job/r/r2devops-bot/gitlab-terraform_plan/latest.yaml
  - remote: https://api.r2devops.io/job/r/r2devops-bot/gitlab-terraform_apply/latest.yaml

.parallel: &parallel
  parallel:
    matrix:
      - TF_ROOT: ${CI_PROJECT_DIR}/terraform/gitlab
        TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/gitlab
      - TF_ROOT: ${CI_PROJECT_DIR}/terraform/prod/k8s-cluster
        TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/prod-cluster
      - TF_ROOT: ${CI_PROJECT_DIR}/terraform/staging/k8s-cluster
        TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/staging-cluster
      - TF_ROOT: ${CI_PROJECT_DIR}/terraform/dev/k8s-cluster
        TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/dev-cluster

gitlab-terraform_plan:
  before_script:
    - cat ${GITLAB_TFVARS} > ${TF_ROOT}/terraform.tfvars
  <<: *parallel
  only:
    refs:
      - merge_requests
      - web
    changes:
      - ${TF_ROOT}/**
gitlab-terraform_apply:
  before_script:
    - cat ${GITLAB_TFVARS} > ${TF_ROOT}/terraform.tfvars
  <<: *parallel
  only:
    refs:
      - merge_requests
      - web
    changes:
      - ${TF_ROOT}/**
  dependencies:
    - gitlab-terraform_plan
