variable "kubeconfig_context_name" {
  type    = string
  default = "k3d-staging-polycode"
}

variable "kubeconfig_path" {
  type    = string
  default = "~/.kube/config"
}

variable "container_registry_password" {
  type        = string
  description = "The password generated by the deploy token used to access the container registry"
  sensitive   = true
}
